export const AIRPORT_CODES: Record<string, string> = {
  "LHR": "London",
  "DXB": "Dubai",
  "JFK": "New York",
  "CDG": "Paris",
  "AMS": "Amsterdam",
  "FRA": "Frankfurt",
  "SIN": "Singapore",
  "HKG": "Hong Kong",
  "LAX": "Los Angeles",
  "SYD": "Sydney",
  "HND": "Tokyo",
  "NRT": "Tokyo",
  "PEK": "Beijing",
  "YYZ": "Toronto",
  "MAD": "Madrid",
  "BCN": "Barcelona",
  "FCO": "Rome",
  "MUC": "Munich",
  "ZRH": "Zurich",
  "CPH": "Copenhagen",
  "OSL": "Oslo",
  "ARN": "Stockholm",
  "HEL": "Helsinki",
  "VIE": "Vienna",
  "SFO": "San Francisco",
  "ORD": "Chicago",
  "ATL": "Atlanta",
  "DFW": "Dallas",
  "DEN": "Denver",
  "SEA": "Seattle",
  "MIA": "Miami",
  "BOS": "Boston",
  "IAD": "Washington D.C.",
  "EWR": "Newark",
  "DOH": "Doha",
  "BKK": "Bangkok",
  "ICN": "Seoul",
  "KUL": "Kuala Lumpur",
  "TPE": "Taipei",
  "MEL": "Melbourne",
  "BNE": "Brisbane",
  "AKL": "Auckland",
  "JNB": "Johannesburg",
  "CPT": "Cape Town",
  "CAI": "Cairo",
  "IST": "Istanbul",
  "ATH": "Athens",
  "LIS": "Lisbon",
  "BRU": "Brussels",
  "GVA": "Geneva",
  "MXP": "Milan",
  "MXV": "Mexico City",
  "GRU": "São Paulo",
  "EZE": "Buenos Aires",
  "BOG": "Bogotá",
  "LIM": "Lima",
  "SCL": "Santiago",
  "DTW": "Detroit",
  "PHL": "Philadelphia",
  "CLT": "Charlotte"
};

export const AIRLINE_CODES: Record<string, string> = {
  "DL": "Delta Air Lines",
  "AA": "American Airlines",
  "UA": "United Airlines",
  "WN": "Southwest Airlines",
  "BA": "British Airways",
  "AF": "Air France",
  "LH": "Lufthansa",
  "EK": "Emirates",
  "QR": "Qatar Airways",
  "SQ": "Singapore Airlines",
  "CX": "Cathay Pacific",
  "JL": "Japan Airlines",
  "NH": "All Nippon Airways",
  "KL": "KLM",
  "QF": "Qantas",
  "AC": "Air Canada",
  "NZ": "Air New Zealand",
  "TK": "Turkish Airlines",
  "EY": "Etihad Airways",
  "VS": "Virgin Atlantic",
  "FR": "Ryanair",
  "U2": "easyJet",
  "B6": "JetBlue",
  "AS": "Alaska Airlines",
  "NK": "Spirit Airlines",
  "F9": "Frontier Airlines"
};

export function getCityName(iataCode: string): string {
  const code = (iataCode || "").trim().toUpperCase();
  return AIRPORT_CODES[code] || code;
}

export function getCarrierName(carrierCode: string): string {
  const code = (carrierCode || "").trim().toUpperCase();
  return AIRLINE_CODES[code] || carrierCode;
}
